/**
 * @file The single source of truth for this demo's two server-only Workers AI model tiers
 * (docs/07-PR-REVIEW-AGENT.md, "Reviewer Personas And Structured Findings"). Unlike
 * `demos/ai-chat/src/models.ts`, this module is **never imported by `src/client/`** -- the
 * reviewer -> model mapping is a fixed, server-only implementation detail never exposed to the
 * browser (docs/07-PR-REVIEW-AGENT.md, "Out Of Scope": "Any client-visible model picker").
 *
 * Both ids are checked with `satisfies` against `keyof AiModels`, the ambient global type
 * generated by `generate-wrangler-types` from `wrangler.jsonc` (see `worker-configuration.d.ts`,
 * gitignored, regenerated by `npm run generate:types`) -- a typo or a retired model id becomes a
 * compile error here rather than a runtime 404 from `env.AI.run()`/`workers-ai-provider`.
 */

/** Which of the two server-only model tiers a reviewer persona is assigned
 * (`src/worker/review/personas/`). */
export type ModelTier = "fast" | "deep";

/** Static metadata for one model tier. Every field here is data -- no function values. */
export interface ModelTierDescriptor {
  /** Exact Workers AI model identifier, called by **literal model id** (never a dynamic route --
   * docs/07-PR-REVIEW-AGENT.md, "Cost Tracking": a literal id is what keeps
   * `env.AI.aiGatewayLogId` populated, per docs/DECISIONS.md #13). */
  readonly id: string;
  /** Human-readable label, used only in structured logs/D1 -- never rendered to an end user
   * picking a model (there is no such picker in this demo). */
  readonly displayName: string;
}

/**
 * The two model tiers (docs/07-PR-REVIEW-AGENT.md, "Reviewer Personas And Structured Findings"):
 * `fast` for the code-quality and accessibility passes, `deep` for architecture and security.
 * Both ids are reused verbatim from `demos/ai-chat/src/models.ts`'s already-verified catalog.
 */
export const MODEL_TIERS = {
  fast: {
    id: "@cf/ibm-granite/granite-4.0-h-micro",
    displayName: "Granite 4.0 H Micro",
  },
  deep: {
    id: "@cf/deepseek-ai/deepseek-r1-distill-qwen-32b",
    displayName: "DeepSeek R1 Distill Qwen 32B",
  },
} as const satisfies Record<
  ModelTier,
  ModelTierDescriptor & { id: keyof AiModels }
>;

/**
 * Look up a model tier's literal model id.
 *
 * @param tier The reviewer persona's assigned tier (`src/worker/review/personas/`).
 * @returns The exact Workers AI model id to call for this tier.
 */
export function modelIdForTier(tier: ModelTier): string {
  return MODEL_TIERS[tier].id;
}
