import { ProblemDetailsError } from "@adrianhall/cloudflare-toolkit/problem-details";
import { describe, expect, it } from "vitest";
import {
  validateCreateTodoInput,
  validateTodoId,
  validateUpdateTodoInput,
} from "./validation";

/** Assert that an input validator throws an RFC 9457 problem with the expected shape. */
function expectProblem(
  fn: () => unknown,
  expected: { detail: string; status: number },
): void {
  try {
    fn();
    expect.unreachable("expected fn to throw");
  } catch (error) {
    expect(error).toBeInstanceOf(ProblemDetailsError);
    expect((error as ProblemDetailsError).problemDetails).toMatchObject(
      expected,
    );
  }
}

describe("validateCreateTodoInput", () => {
  it("trims a valid title", () => {
    expect(validateCreateTodoInput({ title: "  Buy milk  " })).toEqual({
      title: "Buy milk",
    });
  });

  it.each([null, "task", [], 42])("rejects a non-object body: %j", (value) => {
    expectProblem(() => validateCreateTodoInput(value), {
      detail: "The request body must be an object.",
      status: 400,
    });
  });

  it.each([{}, { title: "" }, { title: " ".repeat(281) }])(
    "rejects an invalid title: %j",
    (value) => {
      expectProblem(() => validateCreateTodoInput(value), {
        detail:
          "title" in value
            ? "title must be between 1 and 280 characters."
            : "title is required.",
        status: 422,
      });
    },
  );
});

describe("validateUpdateTodoInput", () => {
  it("accepts either mutable field or both fields", () => {
    expect(validateUpdateTodoInput({ completed: true })).toEqual({
      completed: true,
    });
    expect(
      validateUpdateTodoInput({ completed: false, title: "Renamed" }),
    ).toEqual({
      completed: false,
      title: "Renamed",
    });
  });

  it.each([{}, { completed: "true" }, { unexpected: true }])(
    "rejects an invalid update: %j",
    (value) => {
      expectProblem(() => validateUpdateTodoInput(value), {
        detail:
          "completed" in value
            ? "completed must be a boolean."
            : "Supply title and/or completed only.",
        status: 422,
      });
    },
  );
});

describe("validateTodoId", () => {
  it("accepts UUIDs generated by the Worker", () => {
    expect(validateTodoId("5d837139-c37f-4fe3-b95c-69757a3a823d")).toBe(
      "5d837139-c37f-4fe3-b95c-69757a3a823d",
    );
  });

  it("returns a not-found problem for malformed IDs", () => {
    expectProblem(() => validateTodoId("not-a-todo"), {
      detail: "TODO not found.",
      status: 404,
    });
  });
});
