/**
 * @file The single source of truth for the AI Model Playground's curated model catalog. Both the
 * Worker (`src/worker/chat/`, for validation and adapter selection) and the browser (the model
 * selector) import this module, so it contains **data and pure lookups only** — no adapter
 * implementations and no Worker-only imports (see docs/05-AI-CHAT.md, "Model Catalog").
 *
 * Every `id` is checked with `satisfies` against `keyof AiModels`, the ambient global type
 * generated by `generate-wrangler-types` from `wrangler.jsonc` (see `worker-configuration.d.ts`,
 * gitignored, regenerated by `npm run generate:types`). A typo or a retired model ID becomes a
 * compile error here rather than a runtime 404 from `env.AI.run()`.
 */

/**
 * Which request/response convention a catalog entry's adapter module
 * (`src/worker/chat/adapters/`) uses to call `env.AI.run()` and read its stream. See
 * docs/05-AI-CHAT.md, "Model Adapters", for the verified real behavior behind these two values —
 * notably, `"cf-native"` describes the **input** shape these three models share, not the
 * streaming **output** shape, which differs per model within the group.
 */
export type ModelAdapterId = "cf-native" | "openai-chat";

/**
 * How a model's reasoning (if any) is separated from its answer while streaming. Dispatched by
 * `src/worker/chat/inference.ts`, never guessed at runtime:
 *
 * - `"none"` — every delta is answer text; no Thinking panel appears in the UI.
 * - `"reasoning-field"` — the adapter reads an already-distinct `reasoning_content` delta field.
 * - `"inline-think-tags"` — reasoning arrives inline in the answer text between literal
 *   `<think>`/`</think>` markers, split out by `src/worker/chat/reasoning.ts`.
 */
export type ReasoningMechanism =
  | "none"
  | "reasoning-field"
  | "inline-think-tags";

/** Inclusive bounds and default for one numeric generation parameter. */
export interface ParameterRange {
  /** Value used when the client omits this parameter. */
  readonly default: number;
  /** Minimum accepted value. */
  readonly min: number;
  /** Maximum accepted value. Exceeding it is clamped, never rejected. */
  readonly max: number;
}

/** Bounds and default for the maximum output token count. There is no `min` — `1` always is. */
export interface MaxOutputTokensRange {
  /** Value used when the client omits `maxTokens`. */
  readonly default: number;
  /** Maximum accepted value. Exceeding it is clamped, never rejected. */
  readonly max: number;
}

/**
 * Static metadata for one curated Workers AI text-generation model. Every field here is
 * data — no function values — so this module stays importable from the browser bundle.
 */
export interface ModelDescriptor {
  /** Exact Workers AI model identifier. Never interpolate a client-supplied string here. */
  readonly id: string;
  /** Human-readable name shown in the model selector. */
  readonly displayName: string;
  /** Model provider/vendor, shown alongside `displayName`. */
  readonly provider: string;
  /** Which adapter module in `src/worker/chat/adapters/` calls this model. */
  readonly adapter: ModelAdapterId;
  /** How this model's reasoning (if any) is separated from its answer. */
  readonly reasoning: ReasoningMechanism;
  /** Documented context window, in tokens. Informational only; not enforced by this Worker. */
  readonly contextWindow: number;
  /** Valid temperature bounds and default for this specific model (see docs/05-AI-CHAT.md). */
  readonly temperature: ParameterRange;
  /** Valid output-token-limit bounds and default for this specific model. */
  readonly maxOutputTokens: MaxOutputTokensRange;
}

/**
 * The curated catalog: five models spanning five providers, two adapters, and all three
 * reasoning mechanisms. Kept deliberately small (docs/05-AI-CHAT.md, "Model Catalog", rule 1).
 *
 * Bounds below are verified against a live streaming spike on 2026-07-31, not only the model
 * catalog page — see docs/DECISIONS.md #10 for what the spike corrected relative to the
 * documented/generated-type defaults (most notably Llama 4 Scout's real temperature ceiling).
 */
export const MODEL_CATALOG = [
  {
    id: "@cf/ibm-granite/granite-4.0-h-micro",
    displayName: "Granite 4.0 H Micro",
    provider: "IBM",
    adapter: "cf-native",
    reasoning: "none",
    contextWindow: 131_000,
    temperature: { default: 0.6, min: 0, max: 5 },
    maxOutputTokens: { default: 256, max: 2048 },
  },
  {
    id: "@cf/meta/llama-4-scout-17b-16e-instruct",
    displayName: "Llama 4 Scout 17B",
    provider: "Meta",
    adapter: "cf-native",
    reasoning: "none",
    contextWindow: 131_000,
    // Spike-corrected: this model's real ceiling is 2, not the 0-5 range its shared input type
    // suggests (see docs/DECISIONS.md #10). Clamping is per-descriptor for exactly this reason.
    temperature: { default: 0.7, min: 0, max: 2 },
    maxOutputTokens: { default: 512, max: 2048 },
  },
  {
    id: "@cf/deepseek-ai/deepseek-r1-distill-qwen-32b",
    displayName: "DeepSeek R1 Distill Qwen 32B",
    provider: "DeepSeek",
    adapter: "cf-native",
    reasoning: "inline-think-tags",
    contextWindow: 80_000,
    temperature: { default: 0.6, min: 0, max: 5 },
    // A reasoning model spends output tokens on its <think> block before it ever answers; a
    // higher default and ceiling than the non-reasoning entries keeps that from truncating mid-
    // thought (see docs/05-AI-CHAT.md's inline-think-tags flush behavior for the truncated case).
    maxOutputTokens: { default: 1024, max: 4096 },
  },
  {
    id: "@cf/zai-org/glm-4.7-flash",
    displayName: "GLM 4.7 Flash",
    provider: "Zhipu AI",
    adapter: "openai-chat",
    reasoning: "reasoning-field",
    contextWindow: 131_072,
    temperature: { default: 0.7, min: 0, max: 2 },
    maxOutputTokens: { default: 512, max: 2048 },
  },
  {
    id: "@cf/google/gemma-4-26b-a4b-it",
    displayName: "Gemma 4 26B",
    provider: "Google",
    adapter: "openai-chat",
    reasoning: "reasoning-field",
    contextWindow: 256_000,
    temperature: { default: 0.7, min: 0, max: 2 },
    maxOutputTokens: { default: 512, max: 2048 },
  },
] as const satisfies readonly (ModelDescriptor & { id: keyof AiModels })[];

/** Union of every catalog entry's exact literal `id`. */
export type CatalogModelId = (typeof MODEL_CATALOG)[number]["id"];

/**
 * Look up a catalog entry by exact model ID.
 *
 * @param id Candidate model identifier, typically a client-supplied string from the request body.
 * @returns The matching descriptor, or `undefined` when `id` is not an exact member of
 * {@link MODEL_CATALOG}. Callers MUST treat `undefined` as "reject the request" — never fall back
 * to a default descriptor or interpolate `id` into an `env.AI.run()` call.
 */
export function findModel(id: string): ModelDescriptor | undefined {
  return MODEL_CATALOG.find((descriptor) => descriptor.id === id);
}

/** The catalog entry selected by default in the browser: the cheapest non-reasoning model. */
export const DEFAULT_MODEL_ID: CatalogModelId =
  "@cf/ibm-granite/granite-4.0-h-micro";
