-- Initial migration stub generated by CF Architect.
-- Edit src/db/schema.ts and run `npm run db:generate` to create real migrations.

CREATE TABLE IF NOT EXISTS examples (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL,
  created_at TEXT NOT NULL DEFAULT (datetime('now'))
);
